### ISSUE TITLE
train.py return these errors 

### ISSUE THREAD

**Issue by oshindow** [ZhengkunTian/rnn-transducer#11]
But I can't figure out which one is the 'NoneType' variables.

![image](https://user-images.githubusercontent.com/49552492/79311062-761ca280-7f2f-11ea-88ac-65de130dddc9.png)

**Comment by oshindow** [comment]
Traceback (most recent call last):
  **File "/home/wxt/rnn-transducer-master/train.py", line 218, in <module>**
        main()
  **File "/home/wxt/rnn-transducer-master/train.py", line 193, in main**
        for epoch in range(start_epoch, config.training.epochs):
**TypeError: 'NoneType' object cannot be interpreted as an integer**

**Comment by oshindow** [comment]
hi, the problem is just **'epochs'** in code, but **'epoches'** in timit.yaml

**Comment by BuaaAlban** [comment]
> hi, the problem is just **'epochs'** in code, but **'epoches'** in timit.yaml
hi, can you run it now?  Have you generated the timit feature files using Kaldi example scripts and put them into the author's generated egs/timit/data directory?

**Comment by oshindow** [comment]
> > hi, the problem is just **'epochs'** in code, but **'epoches'** in timit.yaml
> > hi, can you run it now?  Have you generated the timit feature files using Kaldi example scripts and put them into the author's generated egs/timit/data directory?

Yes, I run it successfully now. The only problem is the wrong spelling and the feature files are ok.

**Comment by ZhengkunTian** [comment]
Sorry about that!
