### ISSUE TITLE
LIne 140 in train.py

### ISSUE THREAD

**Issue by oshindow** [ZhengkunTian/rnn-transducer#13]
学长好，train.py 的第140行应该是 'dev' 吗。
另外，prediction network中为什么要用随机的nn.Embedding代替one-hot vector呢?

**Comment by ZhengkunTian** [comment]
不好意思才看到，nn.Embedding 是不是相当于一个One-hot加上一个线性映射的。这个不是啥重要的问题，觉得没必要纠结。
