### ISSUE TITLE
loss值为负数

### ISSUE THREAD

**Issue by Augus-smile** [ZhengkunTian/rnn-transducer#3]
您好，非常感谢您的分享。我在跑您代码的过程中，发现loss值从第一个epoch ，就为负值。且CER刚开始高达600%，最后收敛在100%。具体代码如下，麻烦您看一下，谢谢！
![image](https://user-images.githubusercontent.com/42707701/67682193-bf048d00-f9c9-11e9-9ede-89bf72938eab.png)

**Comment by xuliwalker** [comment]
Hi, 你好！我也在看这个代码，我想请问下准备数据里的utt2spk这些可以从哪获取呢

**Comment by BuaaAlban** [comment]
> Hi, 你好！我也在看这个代码，我想请问下准备数据里的utt2spk这些可以从哪获取呢

我把TIMIT原始数据集下载下来了，目前也是不知道这些utt2spk和feat怎么整，似乎和Kaldi有关，有新消息了互通有无

**Comment by ZhengkunTian** [comment]
请检查计算损失函数的时候数据维度，是否符合要求。出现负值是数据维度的问题。
