### ISSUE TITLE
A question of recognize function implement

### ISSUE THREAD

**Issue by huangnengCSU** [ZhengkunTian/rnn-transducer#4]
Hi:
    In the implement of Transducer.recognize(), the prediction length is equal to or less than input length. In reality, I think the prediction length can longer than input length. I refered to HawkAaron/RNN-Transducer implemention, it has a `While True` recurrent in each iteration of input length which guarantees the prediction length can bigger than input length.

**Comment by ZhengkunTian** [comment]
Sorry, I didn't notice the issue. From the experimental results, there is no problem in this setting.
