### ISSUE TITLE
Structure of egs/timit/data/{train,dev,test} 

### ISSUE THREAD

**Issue by someshjaishwal** [ZhengkunTian/rnn-transducer#7]
Hi, 
Thanks for sharing the implementation. I'm unable to comprehend the structure of  egs/timit/data/{train,dev,test} directories. Can you please help me with that?

**Comment by BuaaAlban** [comment]
> Hi,
> Thanks for sharing the implementation. I'm unable to comprehend the structure of egs/timit/data/{train,dev,test} directories. Can you please help me with that?

Have you solve the problem?? I aslo don't know how the author resturcture the timit dataset directories

**Comment by ZhengkunTian** [comment]
Sorry, I will release a complete version soon. You can deal with your data by kaldi toolkit.

**Comment by BuaaAlban** [comment]
> Sorry, I will release a complete version soon. You can deal with your data by kaldi toolkit.

That will be great, 老铁加油奥力给！ I am an noob in pre-processing of ASR, I will learn kaldi this weekend, wish the complete version could be done soon.

**Comment by BuaaAlban** [comment]
> Sorry, I will release a complete version soon. You can deal with your data by kaldi toolkit.

Hi, how are things going on,will you release a complete version this week? I have learned kaldi and find the script for TIMIT in its example ''/egs/s5/'', are the files in your path <egs/timit/data/{train,dev,test}>  the self-prepared files <text,wac.scp,utt2spk> and generated feature files <feat.scp, cmvn.scp>? 
ps, does your project need the directory <lang>?

looking forward to your reply and thanks a lot for your guidance
