### ISSUE TITLE
请问160维MFCC特征是如何产生的？

### ISSUE THREAD

**Issue by RenJinan** [ZhengkunTian/rnn-transducer#8]
请问160维MFCC特征是如何产生的？mfcc.conf 的参数该如何设置

**Comment by liuming5467** [comment]
他是提的40维mfcc context左边加三帧 tensor变成了4帧的输入 4*40

**Comment by ZhengkunTian** [comment]
对的，采用拼帧的方法来扩充特征。一般是左边拼接3帧。

**Comment by PeiyanFlying** [comment]
> 他是提的40维mfcc context左边加三帧 tensor变成了4帧的输入 4*40
请问我使用了kaldi提取后，是16维，如何也能设置成40维呢？谢谢！
